/**
 * Compiles the Tailwind stylesheet out of band and emits it as a JS module
 * exporting a string.
 *
 * This is deliberately outside pcf-scripts' pipeline: the control imports
 * `uiStyles` as an ordinary ESM string binding and injects it into a <style>
 * element at runtime, so the PCF webpack build needs no postcss loader, no
 * css-loader and no style-loader.
 *
 * Three steps:
 *   1. run the Tailwind CLI exactly as documented (`-i`, `-o`, `--minify`)
 *   2. scope any rule Tailwind emits outside `.di-root`
 *   3. verify the result, then write `styles.js` / `styles.d.ts`
 *
 * Step 2 exists because `important: '.di-root'` scopes *utilities* but not
 * Tailwind's `@defaults` block, which it emits as
 * `*,::before,::after,::backdrop{--tw-...}` even with preflight disabled. That
 * is a global rule reaching into the host app, so it gets scoped here.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(pkgRoot, 'dist');
const cssOut = join(dist, 'styles.css');
const SCOPE = '.di-root';

mkdirSync(dist, { recursive: true });

// --- 1. compile ------------------------------------------------------------

// Resolve the CLI through the module graph rather than a `.bin` path: this
// workspace uses a hoisted node_modules (pcf-scripts needs it), so the shim
// only exists at the repo root, not beside this package.
const require = createRequire(import.meta.url);
const tailwindCli = require.resolve('tailwindcss/lib/cli.js');

execFileSync(
  process.execPath,
  [
    tailwindCli,
    '--config',
    join(pkgRoot, 'tailwind.config.ts'),
    '--input',
    join(pkgRoot, 'src/styles/tailwind.css'),
    '--output',
    cssOut,
    '--minify',
  ],
  { cwd: pkgRoot, stdio: ['ignore', 'ignore', 'inherit'] },
);

// --- 2. scope --------------------------------------------------------------

/** True for rules whose selectors are keyframe stops (`from`, `to`, `40%`). */
function isKeyframeRule(rule) {
  for (let parent = rule.parent; parent; parent = parent.parent) {
    if (parent.type === 'atrule' && /keyframes$/.test(parent.name)) return true;
  }
  return false;
}

function scopeSelector(selector) {
  const trimmed = selector.trim();
  if (trimmed === '' || trimmed.startsWith(SCOPE)) return trimmed;
  // `:root` and a bare `*` must also match the scope element itself, not only
  // its descendants, or the custom properties never reach it.
  if (trimmed === ':root' || trimmed === 'html' || trimmed === ':host') return SCOPE;
  if (trimmed === '*') return `${SCOPE}, ${SCOPE} *`;
  return `${SCOPE} ${trimmed}`;
}

const scopePlugin = {
  postcssPlugin: 'di-scope-everything',
  Rule(rule) {
    if (isKeyframeRule(rule)) return;
    rule.selector = rule.selectors.map(scopeSelector).join(',');
  },
};

// Parsing minified CSS and restringifying preserves its minification: postcss
// reuses the raws it parsed, and only the selectors are rewritten.
const compiled = readFileSync(cssOut, 'utf8');
const scoped = (await postcss([scopePlugin]).process(compiled, { from: cssOut, to: cssOut })).css;
writeFileSync(cssOut, scoped, 'utf8');

// --- 3. verify -------------------------------------------------------------

const problems = [];
const root = postcss.parse(scoped);

if (/(^|[},])\s*\*\s*,\s*::?before/.test(scoped)) {
  problems.push('stylesheet still contains a preflight-style `*,::before` reset');
}

root.walkRules((rule) => {
  if (isKeyframeRule(rule)) return;
  for (const selector of rule.selectors) {
    const trimmed = selector.trim();
    if (trimmed === '') continue;
    if (!trimmed.startsWith(SCOPE)) {
      problems.push(`selector not scoped under ${SCOPE}: ${trimmed}`);
    }
  }
});

if (problems.length > 0) {
  console.error('build-styles: generated CSS is not host-safe:');
  for (const p of [...new Set(problems)].slice(0, 20)) console.error(`  - ${p}`);
  process.exit(1);
}

// --- 4. emit ---------------------------------------------------------------

writeFileSync(
  join(dist, 'styles.js'),
  '// Generated by scripts/build-styles.mjs. Do not edit.\n' +
    `export const uiStyles = ${JSON.stringify(scoped)};\n` +
    'export default uiStyles;\n',
  'utf8',
);

writeFileSync(
  join(dist, 'styles.d.ts'),
  '// Generated by scripts/build-styles.mjs. Do not edit.\n' +
    '/** The compiled, `.di-root`-scoped Tailwind stylesheet, as a string. */\n' +
    'export declare const uiStyles: string;\n' +
    'export default uiStyles;\n',
  'utf8',
);

const ruleCount = root.nodes.length;
console.log(
  `build-styles: emitted dist/styles.css, dist/styles.js and dist/styles.d.ts ` +
    `(${(scoped.length / 1024).toFixed(1)} kB, ${ruleCount} top-level nodes, all scoped under ${SCOPE})`,
);
